CONFIG_HEAP_MEM_POOL_SIZE=8192

CONFIG_NONZERO_SPINLOCK_SIZE=y
CONFIG_PRINTK=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_BOOT_BANNER=n
CONFIG_KERNEL_BIN_NAME="Dust_HeavyRobot"
CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_NAME=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_CPU_LOAD=y
CONFIG_CPU_LOAD_BACKEND_IDLE_HOOK=y
CONFIG_ICACHE=y
CONFIG_DCACHE=n
CONFIG_STATIC_INIT_GNU=y
CONFIG_SPI=y

CONFIG_WARN_DEPRECATED=n
