#pragma once

#define CFG_TUSB_MCU OPT_MCU_HPM
#define CFG_TUSB_OS OPT_OS_ZEPHYR
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_HIGH_SPEED)
#define CFG_TUD_ENABLED 1
#define CFG_TUD_MAX_SPEED OPT_MODE_HIGH_SPEED
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_CDC 1
#define CFG_TUD_CDC_RX_BUFSIZE 1024
#define CFG_TUD_CDC_TX_BUFSIZE 1024
#define CFG_TUD_CDC_RX_EPSIZE 512
#define CFG_TUD_CDC_TX_EPSIZE 512
#define CFG_TUD_MEM_SECTION __attribute__((section("AHB_SRAM")))
#define CFG_TUD_MEM_ALIGN __attribute__((aligned(32)))
